name: Test and deploy on OCI

on:
  push:
    branches: ["main"]

jobs:
  UT:
    runs-on: docker

    steps:
      - uses: actions/checkout@v4

      - name: Install docker-compose
        run: |
          apt-get update && apt-get install docker docker-compose      

      - name: Build and start containers
        run: docker-compose -f docker-compose.yml up -d --build db python

      - name: Wait for DB readiness
        run: |
          for i in {1..10}; do
            docker exec postgres16 pg_isready -U admin && break
            echo "waiting for db..."
            sleep 3
          done

      - name: Run unit tests
        run: docker exec python poetry run pytest -v

      - name: Tear down
        if: always()
        run: docker-compose -f docker-compose.yml down -v