name: Test and deploy

on:
  push:
    branches: ["main"]

jobs:
  UT:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and start containers
        run: docker compose -f docker-compose.test.yml up -d --build db python

      - name: Wait for DB readiness
        run: |
          for i in {1..10}; do
            docker exec postgres16 pg_isready -U admin && break
            echo "waiting for db..."
            sleep 3
          done

      - name: Run unit tests
        run: docker exec python poetry run pytest -v

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.test.yml down -v

  # deploy:
  #   needs: UT
  #   runs-on: ubuntu-latest
  #   # environment: production
  # steps:
  #   - run: echo "Deploy"

  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   - name: Configure AWS credentials
  #     uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: ${{ env.AWS_REGION }}

  #   - name: SSH into EC2 instance, copy files and deploy
  #     id: EC2-actions-docker-compose
  #     env:
  #       host: ${{ secrets.EC2_HOST }}
  #       username: ${{ secrets.EC2_USERNAME }}
  #       key: ${{ secrets.EC2_SSH_KEY }}
  #       port: ${{ secrets.EC2_SSH_PORT }}
  #     run: |
  #       echo "$key" > ssh_key.pem
  #       chmod 500 ssh_key.pem
  #       ssh -i ssh_key.pem -p $port -o StrictHostKeyChecking=no $username@$host 'sudo chmod 777 -R ts'
  #       scp -r -i ssh_key.pem -P $port -o StrictHostKeyChecking=no ./* $username@$host:/home/ec2-user/ts -> git pull instead..
  #       ssh -i ssh_key.pem -p $port -o StrictHostKeyChecking=yes $username@$host 'cd ts && docker-compose -f docker-compose.prod.yml up -d'
