name: Test and deploy

on:
  push:
    branches: ["main"]

jobs:
  # Job 1: Run unit tests
  UT:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------------------------
      - name: Build and start containers
        run: docker compose -f docker-compose.test.yml up -d --build db python

      # -------------------------------------------------
      - name: Wait for DB readiness
        run: |
          for i in {1..10}; do
            docker exec postgres16 pg_isready -U admin && break
            echo "waiting for db..."
            sleep 3
          done

      # -------------------------------------------------
      - name: Run unit tests
        run: docker exec python poetry run pytest -v

      # -------------------------------------------------
      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.test.yml down -v

  # Job 2: Provision Infrastructure with Terraform
  terraform:
    needs: UT
    name: Provision Infrastructure for ${{ matrix.region }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region: [us-east-1] # add or remove as needed, xpl: [us-east-1, eu-west-1, ap-southeast-1]
      fail-fast: false # continue other regions even if one fails

    defaults:
      run:
        working-directory: ./terraform

    steps:
      # -------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # -------------------------------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.region }}

      # -------------------------------------------------
      - name: Terraform Init
        run: terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} init

      # -------------------------------------------------
      - name: Terraform Validate
        run: terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} validate

      # -------------------------------------------------
      - name: Terraform Plan
        run: terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} plan -out=tfplan -var="aws_region=${{ matrix.region }}" -var-file=${GITHUB_WORKSPACE}/terraform/env/dev.tfvars

      # -------------------------------------------------
      - name: Terraform Apply
        run: terraform -chdir=${GITHUB_WORKSPACE}/terraform/regions/${{ matrix.region }} apply -auto-approve tfplan

      # -------------------------------------------------
      - name: Extract EC2 Public IP
        id: ec2
        run: |
          echo "instance_ip=$(terraform output -raw instance_public_ip)" >> $GITHUB_OUTPUT

    outputs: # to use IP in next jobs
      ec2_ip: ${{ steps.extract_ip.outputs.instance_ip }}

  # Job 3: Cloud environment configuration and application deployment with Ansible
  Ansible:
    needs: terraform
    name: Configure Cloud environment (AWS EC2 instance) and deploy application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible #

    steps:
      # -------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------------------------
      - name: Set up Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i "${{ needs.terraform.outputs.ec2_ip }}," -u ubuntu --private-key ~/.ssh/${{ secrets.AWS_SECRET_ACCESS_KEY }} playbook.yml

# Job 2: Infrastructure provisioning via shell script
# launch-ec2: # shell script version
#   needs: UT
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v3

#     - name: Check AWS CLI
#       run: aws --version

#     # - name: Install AWS CLI
#     #   run: sudo apt-get update && sudo apt-get install -y awscli #

#     - name: Launch EC2 instance
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_DEFAULT_REGION: us-east-1
#         AMI_ID: ami-01b9f1e7dc427266e
#         KEY_NAME: ssh-key-1
#         SECURITY_GROUP_ID: sg-08bf60be2d844a0c4
#         INSTANCE_TYPE: t4g.small
#         INSTANCE_NAME: i1
#       run: |
#         bash ec2-launch.sh

# Job 4: Cloud deployment
# deploy:
#   needs: Ansible
#   runs-on: ubuntu-latest
#   # environment: production
#   steps:
#     - run: echo "Deploy"

#     - name: Checkout
#       uses: actions/checkout@v3

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ env.AWS_DEFAULT_REGION }}

#     - name: SSH into EC2 instance, copy files and deploy
#       id: EC2-actions-docker-compose
#       env:
#         host: ${{ env.PUBLIC_IP }}
#         username: ${{ secrets.EC2_USERNAME }}
#         key: ${{ secrets.EC2_SSH_KEY }}
#         port: ${{ secrets.EC2_SSH_PORT }}
#       run: |
#         echo "$key" > ssh_key.pem
#         chmod 500 ssh_key.pem
#         ssh -i ssh_key.pem -p $port -o StrictHostKeyChecking=no $username@$host 'sudo chmod 777 -R fastapi'
#         scp -r -i ssh_key.pem -P $port -o StrictHostKeyChecking=no ./* $username@$host:/home/ubuntu/ts  # -> git pull instead..
#         ssh -i ssh_key.pem -p $port -o StrictHostKeyChecking=yes $username@$host 'cd fastapi && docker-compose -f docker-compose.prod.yml up -d'
